name: pro_video_player_example
description: Example app demonstrating the pro_video_player plugin.
publish_to: 'none' # This example app is not published
version: 1.0.0+1

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  file_picker: ^8.0.0
  flutter:
    sdk: flutter
  pro_video_player:
    path: ../pro_video_player
  pro_video_player_android:
    path: ../pro_video_player_android
  pro_video_player_ios:
    path: ../pro_video_player_ios
  pro_video_player_linux:
    path: ../pro_video_player_linux
  pro_video_player_macos:
    path: ../pro_video_player_macos
  pro_video_player_platform_interface:
    path: ../pro_video_player_platform_interface
  pro_video_player_web:
    path: ../pro_video_player_web
  pro_video_player_windows:
    path: ../pro_video_player_windows

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8

flutter:
  uses-material-design: true
  assets:
    - assets/videos/sample.mp4
    - assets/videos/sample_with_chapters.mp4
    - assets/subtitles/sample_rich_text.ass
    - assets/subtitles/sample_rich_text.vtt
    - assets/subtitles/sample_rich_text.ttml
