name: pro_video_player_android
description: Android implementation of pro_video_player.
version: 0.0.1
repository: https://github.com/user/pro_video_player/tree/main/pro_video_player_android

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  pro_video_player_platform_interface:
    path: ../pro_video_player_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  leak_tracker_flutter_testing: any
  mocktail: ^1.0.4
  pigeon: ^22.7.4

flutter:
  plugin:
    implements: pro_video_player
    platforms:
      android:
        package: dev.pro_video_player.android
        pluginClass: ProVideoPlayerPlugin
        dartPluginClass: ProVideoPlayerAndroid
