name: example_simple_player
description: Simple video player app that opens files from the system or URLs.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  file_picker: ^8.0.0
  flutter:
    sdk: flutter
  pro_video_player:
    path: ../pro_video_player
  pro_video_player_android:
    path: ../pro_video_player_android
  pro_video_player_ios:
    path: ../pro_video_player_ios
  pro_video_player_macos:
    path: ../pro_video_player_macos
  pro_video_player_platform_interface:
    path: ../pro_video_player_platform_interface

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
